[OrdinaryDiffEq]
PrecompileAutoSpecialize = false
PrecompileAutoSwitch = false
PrecompileDefaultSpecialize = false
PrecompileFunctionWrapperSpecialize = false
PrecompileLowStorage = false
PrecompileNoSpecialize = false
PrecompileNonStiff = true
PrecompileStiff = true
