name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  prepare-binders:
    runs-on: ubuntu-latest
    strategy:    
      matrix:
        day: [day1, day2, day3]
    steps:
      - uses: actions/checkout@v3
      - run: rm -r *.toml .gitignore .github
      - run: cp ${{ matrix.day }}/* .
      - run: rm -rf day*
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto-create ${{ matrix.day }} for binder
          branch: ${{ matrix.day }}
          commit_options: '--no-verify --signoff'
          file_pattern: '*.ipynb *.toml'
          repository: .
          commit_user_name: rcds-julia[bot]
          push_options: '--force'
          skip_dirty_check: true
          create_branch: true
